apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-static
spec:
  capacity:
    storage: 5Gi # dummy, size is elastic
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: "" # should be empty in static
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0af13243a1c83c3a6