apiVersion: v1
kind: Pod
metadata: 
 name: multi-containerPort
 labels: 
  purpose: multi-container
spec:
 containers:
 - name: nginx
   image: nginx
 - name: almalinux
   image: almalinux:9
   command: ["sleep","1000"]